version: '3.7'
services:
  charon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - release_version=docker-compose
    image: lukaswire/charon
    container_name: charon
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - charon-db-net

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - charon-db-net


networks:
  charon-db-net:
    driver: bridge