name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set envs
        # set release version to the latest commit
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_SHA}

      - name: Build docker image, push if the branch is master
        uses: docker/build-push-action@v1
        with:
          # login to repo
          repository: lukaswire/charon
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels from the git
          add_git_labels: true
          # push only if this is master
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}

      # Send webhook to Wire using Slack Bot
      - name: Webhook to Wire
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Charon CI pipeline
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_CI }}
        # Send message only if previous step failed
        if: failure()
