name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image, push if the branch is master
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/charon
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
