name: Release Pipeline

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build and publish docker image
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/charon
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version - latest tag
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # push only if this is the build containing tags
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
