name: Release Pipeline

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set envs
          run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Build and publish docker image
        uses: docker/build-push-action@v1
        with:
          repository: lukaswire/charon
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: release_version=${{ env.RELEASE_VERSION }}
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
